language: python
sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

matrix:
  allow_failures:
    - python: pypy

branches:
  only:
    - trunk

addons:
  apt:
    packages:
    - libssl-dev
    - libssl1.0.0

cache:
  directories:
    - $HOME/.cache/pip

env:
  global:
    - TRIAL_REPORTER=text

# Travis-CI has an old version of PyPy so we install a newer version on the
# fly.
# Source: https://github.com/saghul/pycares/blob/master/.travis.yml
install:
  - |
      if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
        export PYENV_ROOT="$HOME/.pyenv"
        if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
          pushd "$PYENV_ROOT" && git pull && popd
        else
          rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
        fi
        export PYPY_VERSION="5.3"
        "$PYENV_ROOT/bin/pyenv" install --skip-existing "pypy-$PYPY_VERSION"
        virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
        source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
        echo "import sys; sys.setrecursionlimit(10000)" > $HOME/virtualenvs/pypy-$PYPY_VERSION/
/lib-python/2.7/sitecustomize.py
      fi
  - pip install tox tox-travis


# FIXME: https://twistedmatrix.com/trac/ticket/8373
# By default, Travis only clones one branch.
# Some tests require the presence of the `trunk` branch so here we are, also
# fetching `trunk` for each test.
before_script:
  - git remote set-branches --add origin trunk
  - git fetch origin trunk

script:
  - tox
