language: python
sudo: false

addons:
  apt:
    packages:
    - libssl-dev
    - libssl1.0.0

cache:
  directories:
    - $HOME/.cache/pip

# python:
#   - "2.7"
#   - "3.3"
#   - "3.4"
#   - "3.5"

matrix:
  include:
    - language: generic
      os: osx
      # 7.1 is OS X 10.10.x
      # see: https://docs.travis-ci.com/user/languages/objective-c/#Supported-OS-X-iOS-SDK-versions
      osx_image: xcode7.1
      env: TOXENV=py27-coverage-publish-posix

env:
  global:
    - TRIAL_REPORTER=text

# Install packages in a virtualenv.
# Install the virtualenv if required.
# Install Python version if required.
install:
  - ./.travis/install.sh tox tox-travis


# FIXME: https://twistedmatrix.com/trac/ticket/8373
# By default, Travis only clones one branch.
# Some tests require the presence of the `trunk` branch so here we are, also
# fetching `trunk` for each test.
before_script:
  - git remote set-branches --add origin trunk
  - git fetch origin trunk

# Run tox from the created virtualenv.
script:
  - tox
