version: '{branch}-{build}'

# No need for Python.
build: off
# Don't build branch if there is a open PR, to prevent double builds.
skip_branch_with_pr: true

cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:
  global:
    TRIAL_REPORTER: text

  # Only use pre-installed Python versions, which Appveyor may upgrade to
  # a later point release.
  # See: http://www.appveyor.com/docs/installed-software#python
  matrix:
    - PYTHON: C:\Python27-x64
      TOXENV: py27-coverage-windows

install:
  # Get some information about the build environment.
  - ps: "ls \"C:/\""
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""
  - ps: echo $env:PYTHON $env:TOXENV
  # Check that we have the expected version and architecture for Python
  - "%PYTHON%\\python --version"
  - "%PYTHON%\\python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # The build system itself is handled by tox.
  - "%PYTHON%\\Scripts\\pip install tox"

test_script:
  - "%PYTHON%\\python -m tox -e %TOXENV%"

# Always push coverage, even if tests failed.
# This should be removed once coverage is pushed from tox.
on_finish:
  - "%PYTHON%\\Scripts\\pip install codecov"
  - "%PYTHON%\\python -m coverage combine"
  - "%PYTHON%\\python -m coverage xml"
  - "%PYTHON%\\python -m codecov"
