#
# Some help for Python on AppVeyor:
# * https://packaging.python.org/appveyor/
# * https://ci.appveyor.com/tools/validate-yaml

version: '{branch}-{build}'

# No need for Python.
build: off
# Don't build branch if there is a open PR, to prevent double builds.
skip_branch_with_pr: true

cache:
  - '%LOCALAPPDATA%\pip\Cache'


environment:
  global:
    TRIAL_REPORTER: text

  # Only use pre-installed Python versions, which Appveyor may upgrade to
  # a later point release.
  # See: http://www.appveyor.com/docs/installed-software#python
  matrix:
    - PYTHON: C:\Python27-x64
      TOXENV: py27-coverage-publish-windows
    - PYTHON: C:\Python35-x64
      TOXENV: py35-coverage-publish-windows


matrix:
  allow_failures:
    # Python 3 is not yet fully ported on Windows.
    - PYTHON: C:\Python35-x64


install:
  # Get some information about the build environment.
  - ps: "ls \"C:/\""
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""
  - ps: echo $env:PYTHON $env:TOXENV
  # Check that we have the expected version and architecture for Python
  - "%PYTHON%\\python --version"
  - "%PYTHON%\\python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # The build system itself is handled by tox.
  - "%PYTHON%\\Scripts\\pip install tox"

test_script:
  - "%PYTHON%\\python -m tox -e %TOXENV%"
