#
# For documentation see https://codecov.io/gh/twisted/twisted/settings/yaml
#
# We want 100% coverage for new patches to make sure we are always increasing
# the coverage.
#
# For now codecov.io has no way to fail if project overall coverage is
# decreased... but I think this is hard as for example if we deprecated and
# remove some code which is well covered we might end up with a smaller
# coverage.
#
coverage:
  precision: 2
  round: down
  status:
    patch:
      default:
        target: 100%

comment:
  layout: "header, diff, uncovered"
  behavior: default
